# Generated by Django 5.2.8 on 2025-11-05 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opep_numero', models.CharField(help_text='Número de OPEP', max_length=50, unique=True)),
                ('nombre_cargo', models.CharField(max_length=255)),
                ('manual_funciones_path', models.CharField(blank=True, help_text='Ruta al manual de funciones', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Cédula de la persona', max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email_personal', models.EmailField(help_text='Email personal para notificaciones', max_length=254, unique=True)),
                ('es_funcionario_antiguo', models.BooleanField(default=False, help_text='Indica si la persona ya es funcionaria')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Resoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(max_length=50, unique=True)),
                ('fecha_resolucion', models.DateField()),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_desfijacion', models.DateField(blank=True, null=True)),
                ('archivo_resolucion_path', models.CharField(blank=True, help_text='Ruta al PDF de la resolución', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
            },
        ),
        migrations.CreateModel(
            name='Procesos_Vinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(choices=[('Nombramiento', 'Nombramiento'), ('Retiro', 'Retiro'), ('Encargo', 'Encargo')], default='Nombramiento', max_length=20)),
                ('numero_th', models.CharField(blank=True, help_text='Consecutivo TH', max_length=50, null=True)),
                ('email_documentacion_destino', models.EmailField(blank=True, help_text='Correo específico para recibir documentos', max_length=254, null=True)),
                ('estado_proceso', models.CharField(choices=[('Pendiente Notificar', 'Pendiente Notificar'), ('Notificado', 'Notificado'), ('Aceptado', 'Aceptado'), ('Pendiente Exámenes', 'Pendiente Exámenes'), ('Docs Completos', 'Docs Completos'), ('Posesionado', 'Posesionado'), ('Rechazado', 'Rechazado')], default='Pendiente Notificar', max_length=50)),
                ('fecha_comunicacion', models.DateTimeField(blank=True, help_text='Fecha y hora de envío de notificación', null=True)),
                ('fecha_maxima_aceptacion', models.DateField(blank=True, null=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, help_text='Fecha y hora de aceptación', null=True)),
                ('fecha_maxima_posesion', models.DateField(blank=True, null=True)),
                ('fecha_solicitud_examenes', models.DateTimeField(blank=True, null=True)),
                ('fecha_citacion_posesion', models.DateTimeField(blank=True, null=True)),
                ('documentos_completos', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='notificaciones.cargos')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='notificaciones.personas')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='notificaciones.resoluciones')),
            ],
            options={
                'verbose_name': 'Proceso de Vinculación',
                'verbose_name_plural': 'Procesos de Vinculación',
                'ordering': ['-id'],
            },
        ),
    ]
