# Generated by Django 5.2.8 on 2025-11-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='email_personal',
            field=models.EmailField(blank=True, help_text='Email personal para notificaciones', max_length=254, null=True, unique=True),
        ),
    ]
