# Generated by Django 5.2.8 on 2025-11-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_personas_email_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos_vinculacion',
            name='proceso_origen',
            field=models.ForeignKey(blank=True, help_text='El proceso (ej. Nombramiento) que origina este proceso (ej. Terminación)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_derivados', to='notificaciones.procesos_vinculacion'),
        ),
        migrations.AlterField(
            model_name='procesos_vinculacion',
            name='tipo_proceso',
            field=models.CharField(choices=[('Nombramiento', 'Nombramiento'), ('Retiro', 'Retiro'), ('Encargo', 'Encargo'), ('Terminacion de Encargo', 'Terminación de Encargo'), ('Insubsistencia', 'Insubsistencia')], default='Nombramiento', max_length=30),
        ),
    ]
