# Generated by Django 5.2.8 on 2025-11-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_procesos_vinculacion_proceso_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos_vinculacion',
            name='tipo_proceso',
            field=models.CharField(choices=[('Nombramiento', 'Nombramiento'), ('Encargo', 'Encargo'), ('Terminacion de Encargo', 'Terminación de Encargo'), ('Insubsistencia', 'Insubsistencia')], default='Nombramiento', max_length=30),
        ),
    ]
